/* Write a function deepEqual that takes two values and returns true only if they are the same value or are objects with the same properties, where the values of the properties are equal when compared with a recursive call to deepEqual. */


function deepEqual(val1, val2) {
    if (val1 === val2) {
        return true;
    
    } else if (typeof(val1) === 'object' && typeof(val2) === 'object' && val1 != null && val2 != null) {
        console.log(Object.keys(val1));
        console.log(Object.keys(val2));
        //the stringfy functions converts the arrays generated by Object.keys into strings so they can be compared with the equality operator
        if (JSON.stringify(Object.keys(val1)) === JSON.stringify(Object.keys(val2))) {
            return true;
        } else return false;
    } else return false;
}

console.log(deepEqual({a:1,z:2,c:2}, {a:1,b:2,c:2}));